### ISSUE TITLE
attempts not incrementing

### ISSUE THREAD

**Issue by pawaroti** [vladimir-yuldashev/laravel-queue-rabbitmq#63]
Attempts counter is not incrementing when job fails and dispatched job is_object()

**Comment by pawaroti** [comment]
Steps to reproduce:

`
class ExampleJob extends Job
{
    public function handle()
    {
        echo $this->attempts();
        throw new \Exception('exception');
    }
}
`

`dispatch(new ExampleJob());`

**Comment by vladimir-yuldashev** [comment]
In version 5.2 it was fixed already.

**Comment by pawaroti** [comment]
composer.json:
`"vladimir-yuldashev/laravel-queue-rabbitmq": "^5.2",`

after:
`rm -rf vendor/ composer.lock && composer clear-cache && composer update`

composer.lock look like:
```
            "name": "vladimir-yuldashev/laravel-queue-rabbitmq",
            "version": "5.2",
            "source": {
                "type": "git",
                "url": "https://github.com/fintech-fab/laravel-queue-rabbitmq.git",
                "reference": "af6b1a8e46e54e0639c47243be4c6292a6e984ab"
            }
```

still the same problem, `$this->attempts()` returns 0

**Comment by pawaroti** [comment]
maybe some problem with updating?

**Comment by pawaroti** [comment]
Can someone confirm that `attempts()` is working correctly with latest 5.2 version?

**Comment by mintopia** [comment]
Hopefully you'll find this fixed now #65 has been merged.

**Comment by pawaroti** [comment]
Yeah it's working now. Thank you very much.

I found some bug i think, in PHP 7.0.6 after adding property `attempts` - on `\VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob:95` and further serialize object `attempts` property is not serialized. It's wired because when i tested it with custom class all works fine, maybe problem is related with `traits` or `extends`.

To fix this issue all you need to do is defining `public $attempts = 0;` property in base `Job` class.

Thanks again for fixing. Cheers.
